changelog:
  categories:
    - title: Product Updates
      labels:
        - feature
        - enhancement

    - title: Fixes
      labels:
        - bug
        - fix

    - title: Docs
      labels:
        - documentation
        - docs

    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies

  exclude:
    labels:
      - skip-changelog

  template: |
    ## Welight CLI Updates

    $CHANGES

    ## Install

    ```bash
    npm i -g welight-cli
    ```
